### PR TITLE
remove circle ci; use travis ci to auto update documentation page. 

### PR DESCRIPTION
**Pull request by leix28**
1. Remove Circle CI from the project. 
2. Update docs. Travis CI now can automatically update the gh-pages branch when the master branch is updated. 
3. [doc here](http://hdi-project.github.io/Trane/)

### CODE REVIEW

**Comment by RogerTangos** [comment]
Hey @leix28 , in tox.ini, I added testing for pythong 3.7. It seems to work. Is there a reason to revert it? It's downloadable at https://www.python.org/downloads/

Otherwise, the PR looks good. I'm glad to see the docs working again.

**Comment by leix28** [comment]
We can add python 3.7 it back. There was some inconsistency between tox.ini and travis.yml. (python  3.7 was set up in tox.ini but not in travis.yml. ) I think that adding python 3.7 back will not cause any problem.

**Comment by leix28** [comment]
OK, so the problem is Python 3.7 has not yet officially supported by Travis.

**Comment by RogerTangos** [comment]
Thank you for merging. (Sorry I was late with this. I meant to do that Monday and just blanked on it.)

**Pull request merged**
