### PR TITLE
reduce the flexibility of Trane to produce useful problems.

### PR DESCRIPTION
**Pull request by leix28**
Only filter and aggregation operation. A new evaluation module.

### CODE REVIEW

**Comment by RogerTangos** [comment]
Hey @leix28  - I like where you're taking the work with `PredictionProblemEvaluator.` I don't think it's necessary to add a new class, `FixWindowCutoffStrategy` though. The existing cutoff strategy is more flexible, and can be used to do the same thing any of the code changes in `CutoffStrategy` or in related `test_` files. I did quite a bit of work to make that possible.

To set up a constant cutoff, it requires you to create a function and pass it to `CutoffStrategy`

```
generate_fn = lambda x : np.datetime64(x['COL_NAME']) -  np.timedelta64(5 ,'D')
cutoff_strategy = CutoffStrategy(generate_fn, "Five days before COL_NAME")
```

It can also handle constant cutoffs. If you'd like, I can show you how to do that.
---
I haven't had time to look at the rest yet, but can do that on Thursday

**Comment by leix28** [comment]
Hi @RogerTangos, thank you very much for your comment. I don't expect you to review the code, and apparently, the code is not product-ready. But I'm very happy to take any advice. 

I changed the cutoff strategy a little bit to try to generate multiple cutoff times for each entity. 
For example, an entity can get 5 cutoff times, say Feb. 1, Mar. 1, ..., Jun. 1, then we can get 5 (feature, label) pairs. Use Jan. data to generate features and use Feb. data to generate labels; Use Feb. data to generate features and use Mar. data to generate labels; etc. In this setting, we can use the first 3 pairs as training data and the last 2 pairs as test data. It makes more sense to me. I'm not sure if we can do this in previous version. 

I'm trying to catch a deadline, so I'll make changes to APIs frequently and the unit test may be out of date, but I'll fix them and make a PR to dev branch eventually.

**Comment by RogerTangos** [comment]
Okie. I understand. Sorry - I didn't want to impose. This just showed up in my notifications and I thought I'd give it a look. Funny you should mention multiple cutoff strategies. I actually implemented it that way originally, but then backtracked after talking with Kalyan about it. Maybe once the deadline's over and if you haven't done it already, I can help work out a decent data structure for `CutoffStrategy` to return.

BTW, to run the tests locally, try `$ tox`. It's a lot faster than having travis rebuild everything, though TBH, that's what I did for my first few commits too.

**Comment by RogerTangos** [comment]
Good luck with the deadline!

**Comment by leix28** [comment]
> Okie. I understand. Sorry - I didn't want to impose. This just showed up in my notifications and I thought I'd give it a look. Funny you should mention multiple cutoff strategies. I actually implemented it that way originally, but then backtracked after talking with Kalyan about it. Maybe once the deadline's over and if you haven't done it already, I can help work out a decent data structure for `CutoffStrategy` to return multiple values. It's very capable of that with only minor code edits.
> 
> BTW, to run the tests locally, try `$ tox`. It's a lot faster than having travis rebuild everything, though TBH, that's what I did for my first few commits too.

I Tried. But lint passes on my local environment. I spent some time to figure that out. The problem is that `trane` is not a known_first_party. After adding that in setup.cfg, I got the same error on my local environment and I can fix the problem.

**Pull request merged**
